# Generated by Django 5.1.2 on 2024-10-16 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="finances.currency",
            ),
        ),
    ]
