# Generated by Django 5.1.2 on 2024-10-16 19:42

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_initial"),
        ("finances", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="finances.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                default=expenses.models.get_default_currency,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="finances.currency",
            ),
        ),
    ]
