# Generated by Django 5.1.2 on 2024-10-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                help_text="Expense category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="expenses.expense_category",
                verbose_name="Category",
            ),
        ),
    ]
