# Generated by Django 5.1.2 on 2024-10-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_expense_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="category",
            new_name="categoryet",
        ),
    ]
