# Generated by Django 5.1.2 on 2024-10-16 20:06

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_rename_categoryet_expense_category"),
        ("finances", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense_category",
            options={"ordering": ["name"], "verbose_name": "Expense Category"},
        ),
        migrations.AlterField(
            model_name="expense",
            name="account",
            field=models.ForeignKey(
                help_text="Expense account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="finances.account",
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Expense amount",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                default=expenses.models.get_default_currency,
                help_text="Expense currency",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="finances.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(help_text="Expense date", verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Expense description",
                max_length=255,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="owner",
            field=models.ForeignKey(
                help_text="Expense owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
