# Generated by Django 5.1.2 on 2024-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input account name",
                        max_length=100,
                        verbose_name="Account",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Input account balance",
                        max_digits=10,
                        verbose_name="Balance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Account_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input account type",
                        max_length=100,
                        verbose_name="Account Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input bank name", max_length=100, verbose_name="Bank"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Input bank country",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input currency full name",
                        max_length=100,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="XXX",
                        help_text="Input currency code",
                        max_length=3,
                        verbose_name="Code",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Input currency symbol",
                        max_length=3,
                        verbose_name="Symbol",
                    ),
                ),
            ],
        ),
    ]
