# Generated by Django 5.1.2 on 2024-10-13 09:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Bank",
                        help_text="Input bank name",
                        max_length=100,
                        verbose_name="Bank name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input bank account type",
                        max_length=100,
                        verbose_name="Bank Account Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankCardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input bank card type",
                        max_length=100,
                        verbose_name="Bank Card Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Bank Account",
                        help_text="Input bank account name",
                        max_length=100,
                        verbose_name="Bank Account name",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Input balance",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Bank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select bank",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.bank",
                        verbose_name="Bank",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select bank account type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.bankaccounttype",
                        verbose_name="Bank Account Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Bank Card",
                        help_text="Input bank card name",
                        max_length=100,
                        verbose_name="Bank Card name",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Input balance",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select bank",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.bank",
                        verbose_name="Bank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select bank card type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.bankcardtype",
                        verbose_name="Bank Card Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Cash",
                        help_text="Input cash name",
                        max_length=100,
                        verbose_name="Cash name",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Input balance",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
