# Generated by Django 5.1.2 on 2024-10-16 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                help_text="Select account owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                help_text="Select account type",
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.account_type",
                verbose_name="Account Type",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                help_text="Select bank",
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.bank",
                verbose_name="Bank",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                help_text="Select currency",
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.currency",
                verbose_name="Currency",
            ),
        ),
    ]
