# Generated by Django 5.1.2 on 2024-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_bankaccount_delete_bankaccout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Input balance",
                max_digits=10,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="bankcard",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Input balance",
                max_digits=10,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Input balance",
                max_digits=10,
                verbose_name="Balance",
            ),
        ),
    ]
