# Generated by Django 5.1.2 on 2024-10-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_alter_bankaccount_balance_alter_bankcard_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Input currency full name",
                        max_length=100,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Input currency short name. Max 3 characters",
                        max_length=3,
                        verbose_name="Short Name",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Input currency symbol",
                        max_length=3,
                        verbose_name="Symbol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.ForeignKey(
                default=1,
                help_text="Select currency",
                on_delete=django.db.models.deletion.PROTECT,
                to="finances.currency",
                verbose_name="Currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankcard",
            name="currency",
            field=models.ForeignKey(
                default=1,
                help_text="Select currency",
                on_delete=django.db.models.deletion.PROTECT,
                to="finances.currency",
                verbose_name="Currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cash",
            name="currency",
            field=models.ForeignKey(
                default=1,
                help_text="Select currency",
                on_delete=django.db.models.deletion.PROTECT,
                to="finances.currency",
                verbose_name="Currency",
            ),
            preserve_default=False,
        ),
    ]
