# Generated by Django 5.1.2 on 2024-10-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_alter_account_options_alter_account_type_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="Input account name",
                max_length=100,
                unique=True,
                verbose_name="Account",
            ),
        ),
    ]
