# Generated by Django 5.1.2 on 2024-10-20 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_alter_account_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="Input account name", max_length=100, verbose_name="Account"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("name", "owner")},
        ),
    ]
