# Generated by Django 5.1.2 on 2024-10-28 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0006_rename_account_type_accounttype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="owner",
            field=models.ForeignKey(
                default=2,
                help_text="Select account type owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bank",
            name="owner",
            field=models.ForeignKey(
                default=2,
                help_text="Select bank owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currency",
            name="owner",
            field=models.ForeignKey(
                default=2,
                help_text="Select currency owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currencies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default=False,
        ),
    ]
