# Generated by Django 5.1.2 on 2024-10-28 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0007_accounttype_owner_bank_owner_currency_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accounttype",
            unique_together={("name", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="bank",
            unique_together={("name", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="currency",
            unique_together={("name", "owner")},
        ),
    ]
