# Generated by Django 5.1.2 on 2024-11-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0008_alter_accounttype_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Balance History",
                "ordering": ["date"],
            },
        ),
    ]
