# Generated by Django 5.1.2 on 2024-11-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_alter_accountbalancehistory_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["bank", "name", "currency"],
                "verbose_name": "Account",
            },
        ),
        migrations.AlterModelOptions(
            name="accountbalancehistory",
            options={"ordering": ["-date"], "verbose_name": "Account Balance History"},
        ),
        migrations.AlterModelOptions(
            name="accounttype",
            options={"ordering": ["name"], "verbose_name": "Account Type"},
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["country", "name"], "verbose_name": "Bank"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["name"], "verbose_name": "Currency"},
        ),
    ]
