# Generated by Django 5.1.2 on 2024-10-17 05:19

import django.db.models.deletion
import transactions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances", "0003_alter_account_options_alter_account_type_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name",
                        max_length=255,
                        unique=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Category description",
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Category owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expense amount",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="Expense date", verbose_name="Date"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Expense description",
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Expense account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finances.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=transactions.models.get_default_currency,
                        help_text="Expense currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finances.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Expense owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Expense category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="transactions.expense_category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "ordering": ["-date"],
            },
        ),
    ]
