# Generated by Django 5.1.2 on 2024-10-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_income_category_expensecategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                help_text="Expense category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="transactions.expensecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                help_text="Income category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to="transactions.incomecategory",
                verbose_name="Category",
            ),
        ),
    ]
