# Generated by Django 5.1.2 on 2024-10-28 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_expense_category_alter_income_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("name", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="incomecategory",
            unique_together={("name", "owner")},
        ),
    ]
