# Generated by Django 5.1.2 on 2024-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_expensecategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(
                help_text="Category name", max_length=255, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="incomecategory",
            name="name",
            field=models.CharField(
                help_text="Category name", max_length=255, verbose_name="Category"
            ),
        ),
    ]
