# Generated by Django 5.1.2 on 2024-11-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_expensecategory_name_alter_incomecategory_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-date", "category", "account"],
                "verbose_name": "Expense",
            },
        ),
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ["-date", "category", "account"],
                "verbose_name": "Income",
            },
        ),
    ]
