# Generated by Django 5.1.2 on 2024-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locale",
            field=models.CharField(
                choices=[
                    ("ru_RU", "Russian"),
                    ("hu_HU", "Hungarian"),
                    ("es_ES", "Spanish"),
                    ("en_US", "English (US)"),
                    ("en_GB", "English (UK)"),
                ],
                default="en_US",
                help_text="Select your preferred locale.",
                max_length=10,
                verbose_name="Locale",
            ),
        ),
    ]
