# Generated by Django 5.1.2 on 2024-10-13 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email", max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram ID",
                max_length=100,
                null=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 254 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must be Alphanumeric",
                        regex="^(?!^me$)[\\w.@+-]+$",
                    )
                ],
                verbose_name="User",
            ),
        ),
    ]
